[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/double-map",
    "pallets/clipbets",
    "pallets/clipbet2",
    "pallets/bblott",
    "runtime",
]
[profile.release]
panic = "unwind"
